
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  key-management:
    image: key-management
    container_name: key-management
    ports:
      - "8080:8080"
    restart: unless-stopped

  token-info:
    image: token-info
    container_name: token-info
    ports:
      - "8082:8082"
    restart: unless-stopped

