PUT http://localhost:8080/keys/b1bf6568-9d97-410b-a7c1-2363d7cce222
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJldmFudGhAZ21haWwuY29tIiwiZXhwIjoxNzQ3NjM4ODc5LCJ1c2VySWQiOjJ9.ceDY5QyXWsvkV9Kpd7wmQy1VGSD1B_OAGDyb-dqyQf0

{
    "rateLimit":150,
    "expiry":1750074438
}